#!/usr/bin/env python3
# This file covered by GPL 3 license
# C. David Horsley 2020
import sys
import os.path
from pycparser import c_parser, c_ast, c_generator, parse_file

class LengthGenerator(c_ast.NodeVisitor):
    def __init__(self, filename, output=None):
        super().__init__()
        self.filename = filename
        if output is None:
            self.output = sys.stdout
        else:
            self.output = output

        self.constants = {}
        self.stack = []
        self.inside_generate_function = False

    def push(self, value):
        self.stack.append(value)
    def pop(self):
        val =  self.stack.pop()
        return val

    def print(self, *args, **kwargs):
        print(*args, file=self.output, **kwargs)

    def add(self):
        v1 = self.pop()
        v2 = self.pop()
        self.push(v1 + v2)

    def mul(self):
        v1 = self.pop()
        v2 = self.pop()
        self.push(v1 * v2)

    def visit_Decl(self, node):
        if node.coord.file != self.filename:
            return
        if self.inside_generate_function:
            raise TypeError
        self.inside_generate_function = True

    def visit_Typedef(self, node):
        if node.coord.file != self.filename:
            return
        if self.inside_generate_function:
            raise TypeError
        self.inside_generate_function = False

        self.print(f"const size_t len_{node.name} = ", end="")

        self.push(0)
        for c in node.type.type.decls:
            self.visit(c)

        value = self.pop()

        self.print(f"{value};")
        self.constants[f"len_{node.name}"] = value


    def visit_ArrayDecl(self, node):
        self.push(int(node.dim.value))
        self.push(0)
        for c in node:
            self.visit(c)
        self.mul()
        self.add()

    def visit_TypeDecl(self, node):
        type = node.type.names[-1]
        name = node.declname

        if type in {'uint8_t', 'int8_t', 'char'}:
            self.push(1)

        elif type in {'uint16_t', 'int16_t'}:
            self.push(2)

        elif type in {'uint32_t', 'int32_t'}:
            self.push(4)

        elif type in {'uint64_t', 'int64_t'}:
            self.push(8)

        else:
            self.push(self.constants[f"len_{type}"])

        self.add()


class UnmarshalGenerator(c_ast.NodeVisitor):
    def __init__(self, filename, endian="little", output=sys.stdout, header=sys.stdout):
        super().__init__()
        self.filename = filename
        self.endian = endian
        self.output = output
        self.header = header

        self.array = False
        self.inside_generate_function = False

        self.print("#include <stdint.h>")
        self.print("#include <sys/types.h>")
        self.print("")
        self.print(f'#include "{filename}"')

        l = LengthGenerator(filename=args.filename, output=self.output)
        l.visit(ast)

    def printheader(self, *args, **kwargs):
        print(*args, file=self.header, **kwargs)

    def print(self, *args, **kwargs):
        print(*args, file=self.output, **kwargs)


    def visit_Typedef(self, node):
        if node.coord.file != self.filename:
            return

        if self.inside_generate_function:
            raise TypeError

        self.inside_generate_function = True

        self.print("")
        self.printheader(
            f"ssize_t unmarshal_{node.name}({node.name} *t, uint8_t *data, size_t n);")
        self.print(
            f"ssize_t unmarshal_{node.name}({node.name} *t, uint8_t *data, size_t n)")
        self.print("{")
        self.print("ssize_t ret; uint8_t *p=data;")
        self.print(f"if (n < len_{node.name}) return -1;")

        for c in node.type.type.decls:
            self.visit(c)

        self.inside_generate_function = False
        self.print("return (p-data);}")

    def visit_ArrayDecl(self, node):
        self.array = True
        self.print(f"for (int i=0; i < {node.dim.value}; i++)" "{")
        for c in node:
            self.visit(c)
        self.array = False
        self.print("}")

    def visit_TypeDecl(self, node):
        type = node.type.names[-1]
        name = node.declname
        if self.array:
            name += "[i]"

        if type in {'uint8_t', 'int8_t', 'char'}:
            self.gen_unmarshal_uint8(name)

        elif type == 'uint16_t':
            self.gen_unmarshal_uint16(name)

        elif type == 'uint32_t':
            self.gen_unmarshal_uint32(name)

        elif type == 'uint32_t':
            self.gen_unmarshal_uint32(name)

        else:
            self.print(f"ret = unmarshal_{type}(&t->{name}, p, n);")
            self.print("p += ret; n -= ret;")

    def gen_unmarshal_uint8(self, name):
        self.print(f"t->{name} = *p++; n--;")

    def gen_unmarshal_uint16(self, name):
        if self.endian == "little":
            self.print(f"t->{name} = (p[0]<<0) | (p[1]<<8); p+=2; n-=2;")
        else:
            self.print(f"t->{name} = (p[1]<<0) | (p[0]<<8); p+=2; n-=2;")

    def gen_unmarshal_uint32(self, name):
        if self.endian == "little":
            self.print(
                f"t->{name} = (p[0]<<0) | (p[1]<<8) | (p[2]<<16) | (p[3]<<24); p+=4; n-=4;")
        else:
            self.print(
                f"t->{name} = (p[3]<<0) | (p[2]<<8) | (p[1]<<16) | (p[0]<<24); p+=4; n-=4;")


INT_TYPES = {'uint8_t', 'int8_t', 'char', 'uint16_t',
             'int16_t', 'uint32_t', 'int32_t', 'uint64_t', 'int64_t', 'int'}

BOOL_TYPES = {'bool'}


class JsonMarshalGenerator(c_ast.NodeVisitor):
    def __init__(self, filename, output=sys.stdout, header=sys.stdout):
        super().__init__()
        self.filename = filename
        self.output = output
        self.header = header

        self.handled = set()
        self.queue = []

        self.inside_typedef = False
        self.inside_generate_function = False
        self.array = False
        self.print("#include <jansson.h>")
        self.print("")
        self.print(f'#include "{filename}"')

    def printheader(self, *args, **kwargs):
        print(*args, file=self.header, **kwargs)

    def print(self, *args, **kwargs):
        print(*args, file=self.output, **kwargs)

    def visit_TypeDecl(self, node: c_ast.TypeDecl):
        if node.coord.file != self.filename:
            return

        if self.inside_generate_function:
            self.generate_statement(node)
            return

        self.generate_function(node)

    def visit_ArrayDecl(self, node):
        # handle strings as special case.
        if node.type.type.names[-1] == "char":
            self.print(
                f"ret = json_stringn(t->{node.type.declname}, {node.dim.value});")
            self.print("if (ret == NULL) return NULL;")
            self.print(
                f'json_object_set_new(root, "{node.type.declname}", ret);')
            return

        self.array = True
        self.print("")
        self.print("a = json_array();")
        self.print("if (a == NULL) return NULL;")
        self.print(f"for (int i=0; i < {node.dim.value}; i++)" "{")
        for c in node:
            self.visit(c)
        self.array = False
        self.print("}")
        self.print(f'json_object_set_new(root, "{node.type.declname}", a);')
        self.print("")

    def visit_Typedef(self, node):
        self.inside_typedef = True
        for c in node:
            self.visit(c)
        self.inside_typedef = False

    def generate_function(self, node: c_ast.TypeDecl, name=None, flat_name=None):
        if self.inside_typedef:
            name = node.declname
            flat_name = name
        elif type(node.type) == c_ast.Struct:
            name = "struct " + node.type.name
            flat_name = '_'.join(name.split())
        else:
            raise TypeError

        if flat_name in self.handled:
            return

        self.print("")
        self.printheader(
            f"json_t *marshal_json_{flat_name}({name} *t);")
        self.print(
            f"json_t *marshal_json_{flat_name}({name} *t)")
        self.print("{")
        self.print("json_t *root = json_object(); json_t *a; json_t *ret;")
        self.print("if (root == NULL) return NULL;")

        self.inside_generate_function = True

        for c in node.type.decls:
            self.visit(c)

        self.inside_generate_function = False

        self.print("return root;}")


    def generate_statement(self, node: c_ast.TypeDecl):
        if type(node.type) == c_ast.Struct:
            if node.type.name is None:
                type_ = "struct_annon_" + str(1)
            else:
                type_ = "struct_" + node.type.name
        else:
            try:
                type_ = node.type.names[-1]
            except AttributeError:
                type_ = node.type.name

            
        name = node.declname
        if name is None:
            raise ValueError

        if self.array:
            name += "[i]"

        if type_ in INT_TYPES:
            self.print(f"ret = json_integer(t->{name});")
        elif type_ in BOOL_TYPES:
            self.print(f"ret = json_boolean(t->{name});")
        else:
            self.queue.append(node)
            self.print(f"ret = marshal_json_{type_}(&t->{name});")

        self.print("if (ret == NULL) return NULL;")

        if self.array:
            self.print("json_array_append_new(a, ret);")
        else:
            self.print(f'json_object_set_new(root, "{name}", ret);')

if __name__ == "__main__":
    import sys
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(
        description='Generate unpacking routines for C struct')
    parser.add_argument('filename', metavar='filename',
                        help='the header file containing the typedefs')
    parser.add_argument('--little', dest='endian', action='store_const', const='little', default='big',
                        help='generate little endian pack/unpack routines (default big endian)')
    args = parser.parse_args()

    ast = parse_file(args.filename, use_cpp=True, cpp_path="gcc",
                     cpp_args=['-E', "-I%s" % (Path(__file__).resolve().parent / 'fake_libc_include')])

    base = os.path.splitext(args.filename)[0]

    with open(base+"_unpack.h", "w+") as unpack_h, \
         open(base+"_unpack.c", "w+") as unpack_c, \
         open(base+"_json.h", "w+") as json_h, \
         open(base+"_json.c", "w+") as json_c:

        # v = UnmarshalGenerator(filename=args.filename,
        #                        endian=args.endian,
        #                        output=unpack_c,
        #                        header=unpack_h,
        #                        )
        # v.visit(ast)
        #
        v = JsonMarshalGenerator(filename=args.filename,
                                 output=json_c,
                                 header=json_h)
        v.visit(ast)
