[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "packgen"
dynamic = ['version']
description = "A tool to generate C struct packing and unpacking routines"
authors = [{ name = "David Horsley", email = "david.e.horsley@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.6"
dependencies = ["pycparser"]

[project.scripts]
packgen = "packgen.__main__:main"

[tool.setuptools_scm]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]
