# This file covered by GPL 3 license
# C. David Horsley 2025
"""Command line entry point."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from packgen.errors import PackgenError
from packgen.generators import json as json_gen
from packgen.generators import pack as pack_gen
from packgen.parser import parse_header
from packgen.version import __version__
from packgen.writer import BANNER_MARK


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="packgen",
        description="Generate packing and unpacking routines for C structs",
    )
    parser.add_argument(
        "filename", metavar="filename", help="the header file containing the typedefs"
    )
    parser.add_argument(
        "--little",
        dest="endian",
        action="store_const",
        const="little",
        default="big",
        help="generate little endian pack/unpack routines (default big endian)",
    )
    parser.add_argument(
        "--big",
        dest="endian",
        action="store_const",
        const="big",
        help="generate big endian pack/unpack routines (the default)",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        default=None,
        help="where to write the generated files (default: alongside the header)",
    )
    parser.add_argument(
        "--no-json",
        dest="json",
        action="store_false",
        help="skip the jansson-based JSON marshallers",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit non-zero if the files on disk are not what "
        "packgen would generate (for CI, where the output is committed)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite output files even if they were not generated by packgen",
    )
    parser.add_argument("--version", action="version", version=f"packgen {__version__}")
    return parser


def _check(out_dir: Path, outputs: dict[str, str]) -> int:
    """Compare generated output against what is already on disk."""
    stale: list[str] = []
    for name, content in outputs.items():
        path = out_dir / name
        try:
            if path.read_text(encoding="utf-8") != content:
                stale.append(f"{path}: out of date")
        except FileNotFoundError:
            stale.append(f"{path}: missing")
        except OSError as exc:
            stale.append(f"{path}: {exc}")

    if not stale:
        return 0
    for line in stale:
        print(f"packgen: {line}", file=sys.stderr)
    print("packgen: re-run packgen to update the generated files", file=sys.stderr)
    return 1


def _unowned(out_dir: Path, outputs: dict[str, str]) -> list[Path]:
    """Output paths that exist but were not written by packgen.

    Generated names are derived from the header, so `packgen foo.h` in a
    tree with a hand-maintained foo_unpack.c would otherwise eat it
    without a word.  Only the banner distinguishes the two.
    """
    found: list[Path] = []
    for name in outputs:
        path = out_dir / name
        try:
            head = path.read_text(encoding="utf-8", errors="replace")[:512]
        except FileNotFoundError:
            continue
        except OSError:
            # Unreadable is not proof it is ours; let the write report it.
            continue
        if BANNER_MARK not in head:
            found.append(path)
    return found


def _write(path: Path, content: str) -> None:
    """Write via a temporary file in the same directory, then rename.

    A crash partway through a multi-file generation should not leave a
    half-written .c that still compiles.
    """
    tmp = path.with_name(f".{path.name}.packgen-tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    header_path = Path(args.filename)
    out_dir = args.output_dir or header_path.parent
    base = header_path.stem

    try:
        schema = parse_header(header_path)
    except PackgenError as exc:
        print(f"packgen: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"packgen: {exc}", file=sys.stderr)
        return 1

    if not schema:
        print(f"packgen: no typedef'd structs found in {header_path}", file=sys.stderr)
        return 1

    unpack_header = f"{base}_unpack.h"
    json_header = f"{base}_json.h"

    outputs: dict[str, str] = {}
    try:
        unpack = pack_gen.generate(
            schema,
            source_header=header_path.name,
            generated_header=unpack_header,
            endian=args.endian,
        )
        outputs[unpack_header] = unpack.header
        outputs[f"{base}_unpack.c"] = unpack.source
    except PackgenError as exc:
        print(f"packgen: {exc}", file=sys.stderr)
        return 1

    if args.json:
        try:
            marshal = json_gen.generate(
                schema,
                source_header=header_path.name,
                generated_header=json_header,
            )
        except PackgenError as exc:
            # The pack routines generated fine; only the JSON ones did not.
            # Say so, because --no-json is then a real way forward.
            print(f"packgen: JSON marshalling: {exc}", file=sys.stderr)
            print(
                "packgen: the pack/unpack routines were fine; "
                "re-run with --no-json to generate just those",
                file=sys.stderr,
            )
            return 1
        outputs[json_header] = marshal.header
        outputs[f"{base}_json.c"] = marshal.source

    if args.check:
        return _check(out_dir, outputs)

    if not args.force:
        unowned = _unowned(out_dir, outputs)
        if unowned:
            for path in unowned:
                print(
                    f"packgen: {path} exists and was not generated by packgen",
                    file=sys.stderr,
                )
            print(
                "packgen: refusing to overwrite; move it aside or pass --force",
                file=sys.stderr,
            )
            return 1

    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in outputs.items():
        _write(out_dir / name, content)
        print(out_dir / name)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
