# This file covered by GPL 3 license
# C. David Horsley 2025
"""A tiny indentation-aware buffer for emitting C."""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from io import StringIO

from packgen.version import __version__

INDENT = "    "

# Recognises packgen's own output. The CLI refuses to overwrite a file
# that does not carry it, so this prefix is load bearing: changing it
# makes every previously generated file look hand written.
BANNER_MARK = "Generated by packgen"


def banner(*, source_header: str, endian: str | None = None) -> str:
    """The `do not edit` comment at the top of every generated file.

    Carries the version and the source header because generated code
    gets committed, and a year later the only way to tell which packgen
    produced a file -- and, crucially, at which byte order -- is if the
    file says so.  Big and little endian output differ only inside the
    shift expressions, so a file regenerated with the wrong flag is a
    silent wire format change.

    Deliberately no timestamp: it would defeat reproducible builds and
    make every regeneration a diff.
    """
    lines = [
        f"/* {BANNER_MARK} {__version__} from {_comment_safe(source_header)}.",
        " * Do not edit.",
    ]
    if endian is not None:
        lines.append(" *")
        lines.append(f" * Byte order: {endian} endian")
    lines.append(" */")
    return "\n".join(lines)


def _comment_safe(text: str) -> str:
    """Neutralise anything that would close the comment early."""
    return text.replace("*/", "*_/")


class Writer:
    """Accumulates lines of C, tracking brace indentation."""

    def __init__(self) -> None:
        self._buffer = StringIO()
        self._level = 0
        self._pending_blank = False

    def line(self, text: str = "") -> None:
        if not text:
            # Collapse runs of blank lines and never start the file with one.
            self._pending_blank = self._buffer.tell() > 0
            return
        if self._pending_blank:
            self._buffer.write("\n")
            self._pending_blank = False
        self._buffer.write(INDENT * self._level + text + "\n")

    def lines(self, *texts: str) -> None:
        for text in texts:
            self.line(text)

    @contextmanager
    def block(self, header: str = "", suffix: str = "") -> Iterator[None]:
        """Emit ``header {`` ... ``}suffix`` with the body indented."""
        self.line(f"{header} {{" if header else "{")
        self._level += 1
        try:
            yield
        finally:
            self._level -= 1
        self.line("}" + suffix)

    @contextmanager
    def function(self, signature: str) -> Iterator[None]:
        """Like :meth:`block`, but with the brace on its own line."""
        self.line(signature)
        with self.block():
            yield

    def getvalue(self) -> str:
        return self._buffer.getvalue()

    def __str__(self) -> str:
        return self.getvalue()


def include_guard(name: str) -> str:
    """A macro name suitable for an include guard, derived from a filename."""
    cleaned = "".join(c.upper() if c.isalnum() else "_" for c in name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return f"PACKGEN_{cleaned}_INCLUDED"
