# This file covered by GPL 3 license
# C. David Horsley 2025
"""A tiny indentation-aware buffer for emitting C."""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from io import StringIO

INDENT = "    "

BANNER = "/* Generated by packgen. Do not edit. */"


class Writer:
    """Accumulates lines of C, tracking brace indentation."""

    def __init__(self) -> None:
        self._buffer = StringIO()
        self._level = 0
        self._pending_blank = False

    def line(self, text: str = "") -> None:
        if not text:
            # Collapse runs of blank lines and never start the file with one.
            self._pending_blank = self._buffer.tell() > 0
            return
        if self._pending_blank:
            self._buffer.write("\n")
            self._pending_blank = False
        self._buffer.write(INDENT * self._level + text + "\n")

    def lines(self, *texts: str) -> None:
        for text in texts:
            self.line(text)

    @contextmanager
    def block(self, header: str = "", suffix: str = "") -> Iterator[None]:
        """Emit ``header {`` ... ``}suffix`` with the body indented."""
        self.line(f"{header} {{" if header else "{")
        self._level += 1
        try:
            yield
        finally:
            self._level -= 1
        self.line("}" + suffix)

    @contextmanager
    def function(self, signature: str) -> Iterator[None]:
        """Like :meth:`block`, but with the brace on its own line."""
        self.line(signature)
        with self.block():
            yield

    def getvalue(self) -> str:
        return self._buffer.getvalue()

    def __str__(self) -> str:
        return self.getvalue()


def include_guard(name: str) -> str:
    """A macro name suitable for an include guard, derived from a filename."""
    cleaned = "".join(c.upper() if c.isalnum() else "_" for c in name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return f"PACKGEN_{cleaned}_INCLUDED"
